name: flutter_study
description: Flutter个人学习专用.
version: 1.0.0+1  # 主版本号.次版本号.修订号
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  english_words:
  cupertino_icons: # 苹果主题图标
  http: # 网络请求
  dio:  # 网络请求
  flare_flutter:  # 2D闪光动画
  nima:  # 2D尼玛动画
  shared_preferences:  # 表单缓存
  fluttertoast:   # 吐司字幕
  flutter_swiper:   # 滑动换屏
  flutter_webview_plugin: 
  event_bus: 
  flutter_slidable:
  carousel_pro: # 轮播图框架
  sqflite:  # sqlite缓存
  transparent_image:  
  url_launcher:
  rxdart:
  flutter_spinkit: 
  font_awesome_flutter:
  polygon_clipper: 
  video_player:
  chewie: 
  built_value:
  built_collection:
  flutter_bloc:
  kiwi:
  json_annotation:
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  built_value_generator:
  json_serializable: 

flutter:
  uses-material-design: true

  assets:
  # 图片资源
  - asset/image/
  # 视频资源
  - asset/video/
  # 2D动画资源
  - asset/animation/
  # Json资源
  - asset/data/