name: flutter_study
description: Flutter个人学习专用.
version: 1.0.0+1  # 主版本号.次版本号.修订号
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: # 苹果主题图标
  http: # 网络请求
  dio:  # 网络请求
  flare_flutter:  # 2D闪光动画
  nima:  # 2D尼玛动画
  shared_preferences:  # 表单缓存
  fluttertoast:   # 吐司字幕
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  assets:
  # 图片资源
  # https://unsplash.com/photos/EN2PucB2yhA
  - assets/image/ronnie-mayo-361348-unsplash.jpg
  # https://unsplash.com/photos/pmH_Y4Qetrk
  - assets/image/stefan-stefancik-105587-unsplash.jpg
  # https://unsplash.com/photos/5ditmO9_ae0
  - assets/image/simon-fitall-530083-unsplash.jpg
  # https://unsplash.com/photos/3MNzGlQM7qs
  - assets/image/anton-repponen-99530-unsplash.jpg
  # https://unsplash.com/photos/CPjkWSD0RM0
  - assets/image/kevin-cochran-524957-unsplash.jpg
  # https://unsplash.com/photos/T0XLKgpyT_c
  - assets/image/samsommer-72299-unsplash.jpg
  # https://unsplash.com/photos/twukN12EN7c
  - assets/image/simon-matzinger-320332-unsplash.jpg
  # https://unsplash.com/photos/8BH_M-53CyA
  - assets/image/meng-ji-102492-unsplash.jpg
  # https://unsplash.com/photos/tvOvBq90bM0
  - assets/image/brady-bellini-212790-unsplash.jpg
  - assets/image/logo.png
  - assets/image/powered_by.png
  - assets/image/icon_list.png
  - assets/image/scene1.png
  - assets/image/scene2.png
  - assets/image/scene3.png
  - assets/image/scene4.png
  - assets/image/scene5.png
  - assets/image/scene6.png
    # 2D动画资源
  - assets/animation/Animals.flr
  - assets/animation/circular.flr
  - assets/animation/Filip.flr
  - assets/animation/Robot.nima
  - assets/animation/robot.png
  - assets/animation/OldMan.nima
  - assets/animation/Hop.nima
  uses-material-design: true