name: flutter_study
description: Flutter个人学习专用.
version: 1.0.0+1  # 主版本号.次版本号.修订号
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: # 苹果主题图标
  http: # 网络请求
  dio:  # 网络请求
  flare_flutter:  # 2D闪光动画
  nima:  # 2D尼玛动画
  shared_preferences:  # 表单缓存
  fluttertoast:   # 吐司字幕
  flutter_swiper:   # 滑动换屏
  flutter_webview_plugin: 
  event_bus: 
  flutter_slidable:
  carousel_pro: # 轮播图框架
  sqflite:  # sqlite缓存
  transparent_image:  
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  # 图片资源
  - assets/image/logo.png
  - assets/image/powered_by.png
  - assets/image/icon_list.png
  - assets/image/scene1.png
  - assets/image/scene2.png
  - assets/image/scene3.png
  - assets/image/scene4.png
  - assets/image/scene5.png
  - assets/image/scene6.png
  - assets/image/avatar.jpg
  - assets/image/splash.png
  - assets/image/avatar.png
  - assets/image/login.png
  - assets/image/logo_zhihu.png
  # 2D动画资源
  - assets/animation/Animals.flr
  - assets/animation/circular.flr
  - assets/animation/Filip.flr
  - assets/animation/Robot.nima
  - assets/animation/robot.png
  - assets/animation/OldMan.nima
  - assets/animation/Hop.nima
  # Json资源
  - assets/data/barchart.json